[package]
name = "transiter"
description = "An Iterator suitable for navigating recursive structures and DAGs"
version = "0.1.0"
license = "MIT"
authors = ["Julian Ganz <neither@nut.email>"]
edition = "2018"
